//! Database handle wrapping toasty's `Db`.
//!
//! Toasty's runtime API takes `&mut Db` for every query. To share the handle
//! across axum's request-handling tasks we wrap it in an async `Mutex`. With a
//! single user and a single agent, contention is negligible.

use std::sync::Arc;
use tokio::sync::Mutex;

use thiserror::Error;

#[derive(Debug, Error)]
pub enum DbError {
    #[error("toasty error: {0}")]
    Toasty(#[from] toasty::Error),
    #[error("postgres error: {0}")]
    Postgres(#[from] tokio_postgres::Error),
    #[error("not found")]
    NotFound,
    #[error("conflict: {0}")]
    Conflict(String),
    #[error("validation: {0}")]
    Validation(String),
}

pub type Result<T> = std::result::Result<T, DbError>;

#[derive(Clone)]
pub struct Db {
    inner: Arc<Mutex<toasty::Db>>,
}

impl Db {
    /// Open a postgres connection and register all models.
    pub async fn connect(url: &str) -> Result<Self> {
        use crate::models::*;
        let db = toasty::Db::builder()
            .models(toasty::models!(
                Setting,
                ApiToken,
                WebSession,
                CurrencyRow,
                Market,
                Broker,
                Account,
                Stock,
                StockTranslation,
                BrokerSymbol,
                Watchlist,
                WatchlistItem,
                Transaction,
                OhlcvDaily,
                FxRateDaily,
                AuditLog,
                IdempotencyKey,
                Sector,
                MacroIndicator,
                MacroObservation,
                NewsItem,
                NewsStockLink,
                NewsSectorLink,
                NewsMacroLink,
                NewsCountryLink,
                NewsTranslation,
                MarketBrief,
                EarningsEvent,
                MacroEvent,
                WatchlistReport,
                ScreenerRun,
                ScreenerHit,
                PortfolioReview,
                Recommendation,
                SelfExam,
                UniverseDefinition,
                CorrelationRun,
                CorrelationPair,
                Catalyst,
                Filing,
                FundamentalsQuarterly,
                AnalystEstimate,
                AnalystRating,
                InsiderTransaction,
                ConnectFlowDaily,
                ConnectHoldingsDaily,
            ))
            .connect(url)
            .await?;
        Ok(Self {
            inner: Arc::new(Mutex::new(db)),
        })
    }

    /// Apply schema. For Phase 0 this delegates to toasty's `push_schema`,
    /// which creates missing tables. Things toasty can't express (ALTER on
    /// existing tables, pgvector columns) are layered on top by
    /// [`Db::post_migrate_sql`].
    pub async fn migrate(&self) -> Result<()> {
        let guard = self.inner.lock().await;
        guard.push_schema().await?;
        Ok(())
    }

}

/// Post-migrate hook. Runs raw SQL via a side `tokio-postgres` connection for
/// things toasty 0.6 can't express:
///   - `news_embeddings` table with a `vector(1536)` column + HNSW index
///     (pgvector type isn't a first-class toasty field type).
///
/// All statements are idempotent (`CREATE ... IF NOT EXISTS`), so this can be
/// safely called on every boot.
pub async fn post_migrate(url: &str) -> Result<()> {
    let (client, connection) = tokio_postgres::connect(url, tokio_postgres::NoTls)
        .await
        .map_err(DbError::from)?;

    // The connection future must be polled for the client to make progress;
    // it ends on disconnect.
    let conn_task = tokio::spawn(async move {
        if let Err(e) = connection.await {
            tracing::warn!("post_migrate side connection ended: {e}");
        }
    });

    client
        .batch_execute(POST_MIGRATE_SQL)
        .await
        .map_err(DbError::from)?;

    drop(client);
    let _ = conn_task.await;
    Ok(())
}

const POST_MIGRATE_SQL: &str = r#"
-- news_translations table. We create it here (rather than via toasty's
-- push_schema) because push_schema isn't idempotent — once any other table
-- exists, it errors before reaching new models. The shape mirrors what toasty
-- would emit for the NewsTranslation model: bigint PK (app-generated), nullable
-- columns for the rest. The UNIQUE on (news_id, locale) is an additional
-- application invariant.
CREATE TABLE IF NOT EXISTS news_translations (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    news_id           BIGINT,
    locale            TEXT,
    title             TEXT,
    summary           TEXT,
    content_md        TEXT,
    agent_summary_md  TEXT,
    translator        TEXT,
    updated_at        TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS news_translations_news_id_idx
    ON news_translations (news_id);

-- market_briefs: daily pre-market and post-market notes. Same idempotency
-- trick (IDENTITY) used here because push_schema can't reach this model on
-- the second migrate.
CREATE TABLE IF NOT EXISTS market_briefs (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country          TEXT,
    kind             TEXT,
    trade_date       TEXT,
    headline         TEXT,
    content_md       TEXT,
    sentiment        TEXT,
    sentiment_score  NUMERIC,
    source           TEXT,
    language         TEXT,
    -- JSON map of locale -> { field: translated_value }. The base columns hold the
    -- canonical (usually English) text; alt-locale strings live here so the
    -- handler can swap them in on `?locale=zh-CN`.
    translations     TEXT,
    created_at       TIMESTAMPTZ,
    updated_at       TIMESTAMPTZ
);
ALTER TABLE market_briefs ADD COLUMN IF NOT EXISTS translations TEXT;
CREATE INDEX IF NOT EXISTS market_briefs_country_idx ON market_briefs (country);
CREATE INDEX IF NOT EXISTS market_briefs_kind_idx ON market_briefs (kind);
CREATE INDEX IF NOT EXISTS market_briefs_date_idx ON market_briefs (trade_date);
CREATE UNIQUE INDEX IF NOT EXISTS market_briefs_natural_key
    ON market_briefs (country, kind, trade_date);

-- earnings_events: per-stock-per-fiscal-period earnings calendar entries.
CREATE TABLE IF NOT EXISTS earnings_events (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_id           BIGINT,
    fiscal_year        INTEGER,
    fiscal_period      TEXT,
    announce_at        TIMESTAMPTZ,
    announce_date      TEXT,
    announce_timing    TEXT,
    status             TEXT,
    eps_estimate       NUMERIC,
    eps_actual         NUMERIC,
    revenue_estimate   NUMERIC,
    revenue_actual     NUMERIC,
    currency           TEXT,
    guidance_md        TEXT,
    notes              TEXT,
    url                TEXT,
    source             TEXT,
    created_at         TIMESTAMPTZ,
    updated_at         TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS earnings_events_stock_idx ON earnings_events (stock_id);
CREATE INDEX IF NOT EXISTS earnings_events_date_idx ON earnings_events (announce_date);
CREATE INDEX IF NOT EXISTS earnings_events_status_idx ON earnings_events (status);
CREATE UNIQUE INDEX IF NOT EXISTS earnings_events_natural_key
    ON earnings_events (stock_id, fiscal_year, fiscal_period);

-- macro_events: discrete policy / data-release events (FOMC, CPI, LPR, …).
CREATE TABLE IF NOT EXISTS macro_events (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    indicator_code      TEXT,
    event_date          TEXT,
    event_kind          TEXT,
    title               TEXT,
    summary_md          TEXT,
    decision            TEXT,
    decision_bps        INTEGER,
    new_value           NUMERIC,
    consensus_estimate  NUMERIC,
    surprise            NUMERIC,
    previous_value      NUMERIC,
    vote                TEXT,
    dot_plot            TEXT,
    url                 TEXT,
    source              TEXT,
    translations        TEXT,
    created_at          TIMESTAMPTZ,
    updated_at          TIMESTAMPTZ
);
ALTER TABLE macro_events ADD COLUMN IF NOT EXISTS translations TEXT;
CREATE INDEX IF NOT EXISTS macro_events_indicator_idx ON macro_events (indicator_code);
CREATE INDEX IF NOT EXISTS macro_events_date_idx ON macro_events (event_date);
CREATE INDEX IF NOT EXISTS macro_events_kind_idx ON macro_events (event_kind);
CREATE UNIQUE INDEX IF NOT EXISTS macro_events_natural_key
    ON macro_events (indicator_code, event_date);

-- watchlist_reports: per-watchlist daily / weekly briefs the agent writes.
CREATE TABLE IF NOT EXISTS watchlist_reports (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    watchlist_id     BIGINT,
    kind             TEXT,
    period_start     TEXT,
    period_end       TEXT,
    headline         TEXT,
    summary_md       TEXT,
    content_md       TEXT,
    sentiment        TEXT,
    sentiment_score  NUMERIC,
    metrics          TEXT,
    notes            TEXT,
    language         TEXT,
    source           TEXT,
    translations     TEXT,
    created_at       TIMESTAMPTZ,
    updated_at       TIMESTAMPTZ
);
ALTER TABLE watchlist_reports ADD COLUMN IF NOT EXISTS translations TEXT;
CREATE INDEX IF NOT EXISTS watchlist_reports_watchlist_idx
    ON watchlist_reports (watchlist_id);
CREATE INDEX IF NOT EXISTS watchlist_reports_kind_idx
    ON watchlist_reports (kind);
CREATE INDEX IF NOT EXISTS watchlist_reports_period_idx
    ON watchlist_reports (period_start);
CREATE UNIQUE INDEX IF NOT EXISTS watchlist_reports_natural_key
    ON watchlist_reports (watchlist_id, kind, period_start);

-- ── Phase 2: agent jobs ─────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS screener_runs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT,
    kind            TEXT,
    run_date        TEXT,
    universe        TEXT,
    universe_size   INTEGER,
    criteria        TEXT,
    description_md  TEXT,
    summary_md      TEXT,
    sentiment       TEXT,
    language        TEXT,
    source          TEXT,
    translations    TEXT,
    created_at      TIMESTAMPTZ,
    updated_at      TIMESTAMPTZ
);
ALTER TABLE screener_runs ADD COLUMN IF NOT EXISTS translations TEXT;
CREATE INDEX IF NOT EXISTS screener_runs_name_idx ON screener_runs (name);
CREATE INDEX IF NOT EXISTS screener_runs_date_idx ON screener_runs (run_date);
CREATE UNIQUE INDEX IF NOT EXISTS screener_runs_natural_key
    ON screener_runs (name, kind, run_date);

CREATE TABLE IF NOT EXISTS screener_hits (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id          BIGINT,
    stock_id        BIGINT,
    rank            INTEGER,
    score           NUMERIC,
    rationale_md    TEXT,
    metrics         TEXT,
    translations    TEXT,
    created_at      TIMESTAMPTZ
);
ALTER TABLE screener_hits ADD COLUMN IF NOT EXISTS translations TEXT;
CREATE INDEX IF NOT EXISTS screener_hits_run_idx ON screener_hits (run_id);
CREATE INDEX IF NOT EXISTS screener_hits_stock_idx ON screener_hits (stock_id);

CREATE TABLE IF NOT EXISTS portfolio_reviews (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind            TEXT,
    period_start    TEXT,
    period_end      TEXT,
    headline        TEXT,
    summary_md      TEXT,
    content_md      TEXT,
    decisions_md    TEXT,
    sentiment       TEXT,
    sentiment_score NUMERIC,
    metrics         TEXT,
    language        TEXT,
    source          TEXT,
    translations    TEXT,
    created_at      TIMESTAMPTZ,
    updated_at      TIMESTAMPTZ
);
ALTER TABLE portfolio_reviews ADD COLUMN IF NOT EXISTS translations TEXT;
CREATE INDEX IF NOT EXISTS portfolio_reviews_kind_idx ON portfolio_reviews (kind);
CREATE INDEX IF NOT EXISTS portfolio_reviews_period_idx ON portfolio_reviews (period_start);
CREATE UNIQUE INDEX IF NOT EXISTS portfolio_reviews_natural_key
    ON portfolio_reviews (kind, period_start);

CREATE TABLE IF NOT EXISTS recommendations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_id        BIGINT,
    sector_code     TEXT,
    action          TEXT,
    confidence      NUMERIC,
    rationale_md    TEXT,
    target_price    NUMERIC,
    target_currency TEXT,
    target_horizon  TEXT,
    issued_at       TIMESTAMPTZ,
    status          TEXT,
    outcome_md      TEXT,
    pnl_pct         NUMERIC,
    closed_at       TIMESTAMPTZ,
    language        TEXT,
    source          TEXT,
    translations    TEXT,
    created_at      TIMESTAMPTZ,
    updated_at      TIMESTAMPTZ
);
ALTER TABLE recommendations ADD COLUMN IF NOT EXISTS translations TEXT;
CREATE INDEX IF NOT EXISTS recommendations_stock_idx ON recommendations (stock_id);
CREATE INDEX IF NOT EXISTS recommendations_status_idx ON recommendations (status);
CREATE INDEX IF NOT EXISTS recommendations_issued_idx ON recommendations (issued_at);

CREATE TABLE IF NOT EXISTS self_exams (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind               TEXT,
    period_start       TEXT,
    period_end         TEXT,
    headline           TEXT,
    content_md         TEXT,
    metrics            TEXT,
    recommendation_ids TEXT,
    notes              TEXT,
    language           TEXT,
    source             TEXT,
    translations       TEXT,
    created_at         TIMESTAMPTZ,
    updated_at         TIMESTAMPTZ
);
ALTER TABLE self_exams ADD COLUMN IF NOT EXISTS translations TEXT;
CREATE INDEX IF NOT EXISTS self_exams_kind_idx ON self_exams (kind);
CREATE UNIQUE INDEX IF NOT EXISTS self_exams_natural_key
    ON self_exams (kind, period_start);

CREATE TABLE IF NOT EXISTS universe_definitions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT UNIQUE,
    description_md  TEXT,
    stock_ids       TEXT,
    created_at      TIMESTAMPTZ,
    updated_at      TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS correlation_runs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind            TEXT,
    run_date        TEXT,
    universe_id     BIGINT,
    lookback_days   INTEGER,
    method          TEXT,
    summary_md      TEXT,
    metrics         TEXT,
    source          TEXT,
    translations    TEXT,
    created_at      TIMESTAMPTZ,
    updated_at      TIMESTAMPTZ
);
ALTER TABLE correlation_runs ADD COLUMN IF NOT EXISTS translations TEXT;
CREATE INDEX IF NOT EXISTS correlation_runs_universe_idx ON correlation_runs (universe_id);
CREATE INDEX IF NOT EXISTS correlation_runs_date_idx ON correlation_runs (run_date);

CREATE TABLE IF NOT EXISTS correlation_pairs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id          BIGINT,
    stock_a_id      BIGINT,
    stock_b_id      BIGINT,
    correlation     NUMERIC
);
CREATE INDEX IF NOT EXISTS correlation_pairs_run_idx ON correlation_pairs (run_id);
CREATE INDEX IF NOT EXISTS correlation_pairs_a_idx ON correlation_pairs (stock_a_id);
CREATE INDEX IF NOT EXISTS correlation_pairs_b_idx ON correlation_pairs (stock_b_id);
CREATE UNIQUE INDEX IF NOT EXISTS correlation_pairs_natural_key
    ON correlation_pairs (run_id, stock_a_id, stock_b_id);

CREATE TABLE IF NOT EXISTS catalysts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_id        BIGINT,
    sector_code     TEXT,
    country         TEXT,
    catalyst_kind   TEXT,
    title           TEXT,
    summary_md      TEXT,
    catalyst_date   TEXT,
    date_confidence TEXT,
    impact_level    TEXT,
    bull_case_md    TEXT,
    bear_case_md    TEXT,
    status          TEXT,
    notes           TEXT,
    url             TEXT,
    source          TEXT,
    translations    TEXT,
    created_at      TIMESTAMPTZ,
    updated_at      TIMESTAMPTZ
);
ALTER TABLE catalysts ADD COLUMN IF NOT EXISTS translations TEXT;
CREATE INDEX IF NOT EXISTS catalysts_stock_idx ON catalysts (stock_id);
CREATE INDEX IF NOT EXISTS catalysts_sector_idx ON catalysts (sector_code);
CREATE INDEX IF NOT EXISTS catalysts_date_idx ON catalysts (catalyst_date);
CREATE INDEX IF NOT EXISTS catalysts_status_idx ON catalysts (status);
CREATE INDEX IF NOT EXISTS catalysts_kind_idx ON catalysts (catalyst_kind);

-- pgvector embeddings table for news. Schema lives outside toasty because the
-- vector type isn't expressible in the derive macro.
CREATE TABLE IF NOT EXISTS news_embeddings (
    news_id     BIGINT PRIMARY KEY REFERENCES news_items(id) ON DELETE CASCADE,
    embedding   vector(1536),
    model       TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS news_embeddings_hnsw
    ON news_embeddings
    USING hnsw (embedding vector_cosine_ops);
"#;

// Re-open the impl so the helpers above are inside the type.
impl Db {
    /// Placeholder to keep the second `impl Db { ... }` block valid in case
    /// future helpers land below the post-migrate definition. No-op.
    #[doc(hidden)]
    pub fn _placeholder(&self) {}

    /// Acquire the underlying toasty handle for a single operation.
    /// Helper modules call this and run their query inside the guard scope.
    pub async fn with<F, R>(&self, f: F) -> R
    where
        F: for<'a> AsyncFnOnce(&'a mut toasty::Db) -> R,
    {
        let mut guard = self.inner.lock().await;
        f(&mut *guard).await
    }
}
