import { form, get, post, route } from 'remix/fetch-router/routes'

export const routes = route({
  assets: get('/assets/*path'),
  home: '/',
  login: form('/login'),
  logout: post('/logout'),
  changePassword: form('/change-password'),
  admin: '/admin',
  adminBrokers: '/admin/brokers',
  adminTokens: '/admin/tokens',
  adminUserCreate: post('/admin/users/new'),
  adminUserReset: post('/admin/users/:id/reset'),
  adminUserDelete: post('/admin/users/:id/delete'),
  adminBrokerCreate: post('/admin/brokers/new'),
  adminBrokerRename: post('/admin/brokers/:id/rename'),
  adminBrokerDelete: post('/admin/brokers/:id/delete'),
  adminTokenCreate: post('/admin/tokens/new'),
  adminTokenRevoke: post('/admin/tokens/:id/revoke'),
  apiKeys: '/api-keys',
  apiKeyCreate: post('/api-keys/new'),
  apiKeyRevoke: post('/api-keys/:id/revoke'),
  accounts: '/accounts',
  accountCreate: post('/accounts/new'),
  accountDelete: post('/accounts/:id/delete'),
  holdings: '/holdings',
  stocks: '/stocks',
  stockDetail: '/stocks/:id',
  watchlists: '/watchlists',
  transactions: '/transactions',
  news: '/news',
  newsDetail: '/news/:id',
  briefs: '/briefs',
  earnings: '/earnings',
  macroEvents: '/macro-events',
  catalysts: '/catalysts',
  screeners: '/screeners',
  recommendations: '/recommendations',
  portfolioReviews: '/portfolio-reviews',
  correlations: '/correlations',
  selfExams: '/self-exams',
  audit: '/audit',
  settings: '/settings',
})
